<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-NLARMDD7" failures="1" tests="2" name="Error Validation Test" time="9.546" errors="0" timestamp="2025-06-13T20:37:23 IST">
  <testcase classname="Automation.Framework.ErrorValidations" name="LogInErrorValidation" time="0.398"/>
  <testcase classname="Automation.Framework.ErrorValidations" name="ProductErrorValidation" time="2.005">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Automation.Framework.ErrorValidations.ProductErrorValidation(ErrorValidations.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error Validation Test -->
